### ISSUE TITLE
Feature Request: Display Director's Name in Discord Rich Presence

### ISSUE THREAD

**Issue by thisanickname** [zeroquinc/KodiDiscord#1]
I would like to propose an enhancement for the Discord rich presence functionality in Kodi. Specifically, it would be great if the rich presence status could also display the name of the director of the currently playing media.

**Comment by zeroquinc** [comment]
Fixed in https://github.com/zeroquinc/KodiDiscord/commit/b1f6b07ad8f95fc65683d4bfef1813af1dd6267d
