### ISSUE TITLE
TV Show poster is is blank

### ISSUE THREAD

**Issue by ghost** [zeroquinc/KodiDiscord#9]
The poster on the discord RPC shows properly when I am watching a movie, but it doesn't show when I start watching a TV Show. It just shows the default poster. Also the buttons don't show up when watching a TV show too
![image](https://github.com/zeroquinc/KodiDiscord/assets/55392066/24a8e522-6c4e-450b-a921-1bd6682301b5)

**Comment by zeroquinc** [comment]
Could you post the debug log when trying to play a TV show? Because you said movies works, I think it has something to do with the script not finding the TMDB ID.

**Comment by ghost** [comment]
where can i find the log to post?
I also i should let you know, i manually changed the base URL, in the globals.py file because kodi is running on a separate system within my lan

**Comment by ghost** [comment]
![image](https://github.com/zeroquinc/KodiDiscord/assets/55392066/4e5907dd-e146-45c1-9387-20e120413861)

**Comment by zeroquinc** [comment]
That should be fine.

I don't think it currently writes it to a file, this was a project when I was starting programming. Just set your logging level to DEBUG, run it in your terminal, start a TV show and post the output here.

**Comment by zeroquinc** [comment]
Closing this as it's an issue with an addon that I sadly can't fix. This script assumes you have local Kodi files.
